'use strict';

var _parser = require('./parser');

module.exports = function (source, map) {
  this.cacheable && this.cacheable();

  var callback = this.async();

  (0, _parser.parseScript)(source).then(function (_ref) {
    var parsed = _ref.parsed;

    var requireList = parsed.match(/require\([^()]+?\)/g);

    if (requireList && requireList.length > 0) {
      requireList = requireList.filter(function (str) {
        if (str.indexOf('@jud-module') > 0) {
          parsed = parsed.replace(str, str.replace('require', '__jud_require__'));
          return true;
        }
        return false;
      }).join('\n');
    }

    var result = 'module.exports = function(module, exports, __jud_require__){' + parsed + '}';
    result += '\n/* generated by jud-loader */\n';
    callback(null, result, map);
  }).catch(function (e) {
    callback(e, '');
  });
};